Controller class added for App user.
johnrichmondjr/d2l-mock pull request #57
Opened 2024-10-27 19:27 UTC by Puneethnaidum

Controller class added.

2024-10-27 22:45 UTC, kpento requested changes
Should the  RequestMapping be changed to "/api/users"?

2024-10-28 00:12 UTC, Puneethnaidum commented
sure ,i will change

2024-10-29 01:16 UTC, StephenStage approved these changes

2024-10-29 01:17 UTC, StephenStage approved these changes

2024-10-29 21:31 UTC, kpento approved these changes

2024-10-29 21:31 UTC, merged